version: '3.8'
services:
  menu_service:
    build:
      context: .
      dockerfile: Dockerfile_menu_service
    ports:
      - "5002:5002"
    volumes:
      - C:/Users/Dmitriy/Desktop/prac6:/data
    depends_on:
      - prometheus
      - grafana

  reservation_service:
    build:
      context: .
      dockerfile: Dockerfile_reservation_service
    ports:
      - "5003:5003"
    volumes:
      - C:/Users/Dmitriy/Desktop/prac6:/data
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    restart: always

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

volumes:
  db_volume:
